# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='threads',
            field=models.ManyToManyField(blank=True, null=True, related_name='board', to='boardapp.Thread'),
        ),
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='thread', to='boardapp.Post'),
        ),
    ]
