# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20160920_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='head',
        ),
    ]
