# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_remove_thread_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
    ]
