# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_remove_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
